Ospf deprecated command
ansible-collections/arista.eos pull request #134
Opened 2020-12-03 19:37 UTC by GomathiselviS

##### SUMMARY

Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/180
Partially fixes : https://github.com/ansible-collections/arista.eos/issues/133

ospf bfd command syntax has changed from 'bfd all-interfaces' to 'bfd default' , starting from eos version 4.23.
This PR has the fix that adds support for the same.

Reference doc: https://www.arista.com/en/support/advisories-notices/fieldnotices/7097-field-notice-39

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
eos_ospfv3 , eos_ospfv2

##### ADDITIONAL INFORMATION

```paste below

```

2020-12-03 19:48 UTC, GomathiselviS commented
recheck

2020-12-04 18:41 UTC, GomathiselviS commented
recheck

2020-12-08 16:30 UTC, NilashishC requested changes

2020-12-08 16:30 UTC, NilashishC commented on plugins/module_utils/network/eos/config/ospfv2/ospfv2.py
> +                os_version = get_capabilities(self._module)["device_info"][
I think if we go through the module_utils route, the Connection object will always be created and `rendered` will no longer work offline. At this point in code, the self._connection object should be set (expect for `rendered` and `parsed`), so we can possibly do something like:
```
if self._connection:
    os_version = self._connection.get_device_info()["network_os_version"]
```
For `rendered`, however, we can compute command strings based on what's valid for the standard EOS version and mention that in the doc.

2020-12-08 16:30 UTC, NilashishC commented on plugins/module_utils/network/eos/rm_templates/ospfv3.py
> +        os_version = get_capabilities(module)["device_info"][
Same comment as above regarding offline feature of `rendered`.

2020-12-08 16:30 UTC, NilashishC commented on plugins/module_utils/network/eos/rm_templates/ospfv3.py
> +        global os_version
Not a big fan of global variables, but I don't have a better solution than this since the methods have always been kept outside of the class.

2021-02-12 18:53 UTC, GomathiselviS commented
recheck

2021-02-22 15:11 UTC, GomathiselviS commented
recheck

2021-02-23 05:45 UTC, NilashishC commented on changelogs/fragments/123-ospfv3-description.yaml
> +  - modify short description in ospfv3 resource module.
Is this changelog fragment valid for this PR?

2021-02-23 19:36 UTC, merged