Mask sensitive key values from module result
ansible-collections/arista.eos pull request #198
Opened 2021-04-08 16:34 UTC by GomathiselviS

Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-04-09 04:39 UTC, NilashishC requested changes
The validate-modules:no-log-needed in ignore-2.11 list can be now be removed.

2021-04-09 14:14 UTC, NilashishC commented
@GomathiselviS this would also need a bump in ansible.netcommon version in galaxy.yml to >=2.0.1. Please refer to https://github.com/ansible-collections/cisco.nxos/pull/278/files#diff-1ade2795a7b410581d689fb0faa358b769c2d189b2d549e8f530b706f09b2fb7R5.

2021-04-19 21:39 UTC, GomathiselviS commented
recheck

2021-04-21 14:37 UTC, NilashishC commented on plugins/module_utils/network/eos/argspec/ospf_interfaces/ospf_interfaces.py
> +                                "keytype": {"type": "str", "no_log": True},
Does keytype sensitive data? If not then we can set no_log: False explicitly to bypass validate-modules.

2021-04-21 14:37 UTC, NilashishC commented on plugins/module_utils/network/eos/argspec/ospf_interfaces/ospf_interfaces.py
> +                                "keytype": {"type": "str", "no_log": True},
Same as above.

2021-04-21 14:40 UTC, NilashishC commented on plugins/module_utils/network/eos/argspec/ospf_interfaces/ospf_interfaces.py
> +                            "no_log": True,
Same discussion as in VyOS PR.

2021-04-22 12:39 UTC, NilashishC approved these changes

2021-04-22 17:16 UTC, merged