Update Docs with boolean normalization
ansible-collections/arista.eos pull request #412
Opened 2023-04-03 13:01 UTC by rohitthakur2590

##### SUMMARY

##### ISSUE TYPE

 
- Docs Pull Request
 

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-04-05 13:06 UTC, Qalthos approved these changes

2023-04-05 16:34 UTC, Qalthos requested changes

2023-04-05 16:34 UTC, Qalthos commented on plugins/modules/eos_config.py
> +    default: true
```suggestion
    default: false
```

2023-04-05 16:34 UTC, Qalthos commented on plugins/modules/eos_config.py
> +    default: true
```suggestion
    default: false
```

2023-04-10 06:11 UTC, rohitthakur2590 commented
recheck

2023-04-10 11:29 UTC, KB-perByte approved these changes

2023-04-12 10:04 UTC, merged